spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bluesea1
    username: root
    password: root#123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true